server:
  port: '5000'

spring:
  cloud:
    gateway:
      routes:
        - id: User-Service
          predicates:
            - Path=/user/**, /address/**
          uri: lb://User-Service
        - id: Product-Service
          predicates:
            - Path=/product/**
          uri: lb://Product-Service
        - id: Order-Service
          predicates:
            - Path=/order/**
          uri: lb://Order-Service
          filters:
            - name: HeaderValidationFilter
              args:
                headerName: XAuth-Header

  application:
    name: API-Gateway
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: 'true'
